### PR TITLE
Remove 'launchers/' prefix from launcher path

### PR DESCRIPTION
**Pull request by rjatkins**
Also fixes up some related exception messages to be more meaningful

### CODE REVIEW

**Comment by scrobbleme** [comment]
#Like 
This is an annyoing bug.

**Comment by andreastt** [comment]
I believe I fixed this in the latest release, 0.9, by fixing the Maven build file for operalaunchers.  Can you verify?

**Comment by scrobbleme** [comment]
Works as expected. Thanks for the fix.

**Comment by rjatkins** [comment]
This appears to be working in 0.9 on windows - it now just gets the error raised in #38 in the first test class we run (luckily, our test suite recreates the webdriver in each test, so the remaining tests get a chance to run). I can still reproduce this with master as well, so I don't think #38 is fixed.

**Pull request closed without merging**
